@BookStore_HostAddress = http://localhost:5105

### Get all books
GET {{BookStore_HostAddress}}/api/books
Accept: application/json

### Get book by id
GET {{BookStore_HostAddress}}/api/books/1
Accept: application/json

### Create a book
POST {{BookStore_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "price": 150000,
  "stock": 10
}

### Update a book
PUT {{BookStore_HostAddress}}/api/books/1
Content-Type: application/json

{
  "title": "Clean Code (2nd Edition)",
  "author": "Robert C. Martin",
  "price": 175000,
  "stock": 8
}

### Delete a book
DELETE {{BookStore_HostAddress}}/api/books/1
